WITH_BIND_SIGCHASE=	yes
WITHOUT_BLACKLIST=	yes
WITHOUT_BLUETOOTH=	yes
WITHOUT_BOOTPARAMD=	yes
WITHOUT_BSDINSTALL=	yes
WITHOUT_BSNMP=		yes
WITHOUT_CCD=		yes
WITH_CTF=		yes
WITHOUT_DMAGENT=	yes
WITHOUT_FLOPPY=		yes
WITHOUT_FREEBSD_UPDATE=	yes
WITHOUT_GPIB=		yes
WITHOUT_GSSAPI=		yes
WITHOUT_HYPERV=		yes
WITHOUT_IPFILTER=	yes
WITHOUT_IPX=		yes
WITHOUT_KERBEROS=	yes
WITHOUT_LEGACY_CONSOLE=	yes
# Do not need 32-bit compatibility libraries
WITHOUT_LIB32=		yes
WITHOUT_LLVM_TARGET_ALL=yes
WITHOUT_LPR=		yes
WITHOUT_OPENSSH=	yes
WITHOUT_PF=		yes
WITHOUT_PPP=		yes
# This is for UFS quotas, we are 100% ZFS
WITHOUT_QUOTAS=		yes
WITHOUT_RADIUS_SUPPORT=	yes
WITHOUT_RBOOTD=		yes
WITHOUT_ROUTED=		yes
WITHOUT_SYSCONS=	yes
WITHOUT_SYSINSTALL=	yes
WITHOUT_TALK=		yes
WITHOUT_TESTS=		yes
# We always want to use the unbound (or bind) from package
WITHOUT_UNBOUND=	yes
# Don't have wireless interfaces on servers
WITHOUT_WIRELESS=	yes

PKGSIGNKEY=		/root/pkg-signing.pem
